const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "238140524998";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_05_32_09_21_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgODgsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjAzLFxuICAgICAgICA3NyxcbiAgICAgICAgMzIsXG4gICAgICAgIDksXG4gICAgICAgIDIwLFxuICAgICAgICAxMTMsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMjU0LFxuICAgICAgICA2MyxcbiAgICAgICAgMTgxLFxuICAgICAgICA3NixcbiAgICAgICAgMTcyLFxuICAgICAgICAyNDMsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTQ2LFxuICAgICAgICA3NyxcbiAgICAgICAgODAsXG4gICAgICAgIDE5LFxuICAgICAgICAxNTUsXG4gICAgICAgIDI0MixcbiAgICAgICAgMTA5LFxuICAgICAgICAxNDAsXG4gICAgICAgIDE1MixcbiAgICAgICAgMjE3LFxuICAgICAgICAxNDgsXG4gICAgICAgIDE4NCxcbiAgICAgICAgMjQ0LFxuICAgICAgICAyMDEsXG4gICAgICAgIDIyNSxcbiAgICAgICAgODVcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjI4LFxuICAgICAgICA5MyxcbiAgICAgICAgNDcsXG4gICAgICAgIDc0LFxuICAgICAgICA5NixcbiAgICAgICAgNzksXG4gICAgICAgIDk4LFxuICAgICAgICA2MCxcbiAgICAgICAgNTksXG4gICAgICAgIDIwLFxuICAgICAgICAxNDMsXG4gICAgICAgIDI0OCxcbiAgICAgICAgOTQsXG4gICAgICAgIDE1LFxuICAgICAgICAxMDIsXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTQ0LFxuICAgICAgICAxNjYsXG4gICAgICAgIDE1NixcbiAgICAgICAgNzYsXG4gICAgICAgIDE5MCxcbiAgICAgICAgODQsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTM0LFxuICAgICAgICAyMzUsXG4gICAgICAgIDkxLFxuICAgICAgICAxMjUsXG4gICAgICAgIDExOSxcbiAgICAgICAgMTc2LFxuICAgICAgICAxNjgsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMjJcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE4NCxcbiAgICAgICAgODYsXG4gICAgICAgIDkzLFxuICAgICAgICAxMjQsXG4gICAgICAgIDQsXG4gICAgICAgIDQ4LFxuICAgICAgICAxODYsXG4gICAgICAgIDE3MixcbiAgICAgICAgMzIsXG4gICAgICAgIDE2MCxcbiAgICAgICAgMTA1LFxuICAgICAgICAxODYsXG4gICAgICAgIDQ1LFxuICAgICAgICAxNTMsXG4gICAgICAgIDE1NixcbiAgICAgICAgMTgxLFxuICAgICAgICAxOCxcbiAgICAgICAgMTUzLFxuICAgICAgICAyMjQsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjQyLFxuICAgICAgICAxNTgsXG4gICAgICAgIDIzMyxcbiAgICAgICAgMjUsXG4gICAgICAgIDExMixcbiAgICAgICAgMTUxLFxuICAgICAgICAxMTAsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMjgsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjAyLFxuICAgICAgICAxMjNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjEyLFxuICAgICAgICAyMDUsXG4gICAgICAgIDksXG4gICAgICAgIDgzLFxuICAgICAgICAyMTYsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxNSxcbiAgICAgICAgMzUsXG4gICAgICAgIDg5LFxuICAgICAgICAxMjAsXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjM4LFxuICAgICAgICAxODYsXG4gICAgICAgIDcxLFxuICAgICAgICAxLFxuICAgICAgICAyNTQsXG4gICAgICAgIDI1NSxcbiAgICAgICAgODUsXG4gICAgICAgIDIwLFxuICAgICAgICAxNDAsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTYxLFxuICAgICAgICAyMTIsXG4gICAgICAgIDY3LFxuICAgICAgICAyMDgsXG4gICAgICAgIDc5LFxuICAgICAgICAxMjgsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTE2LFxuICAgICAgICAxMTQsXG4gICAgICAgIDg3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNjgsXG4gICAgICAgIDYxLFxuICAgICAgICA4LFxuICAgICAgICA2LFxuICAgICAgICAxMjYsXG4gICAgICAgIDIsXG4gICAgICAgIDc4LFxuICAgICAgICAyMzEsXG4gICAgICAgIDY3LFxuICAgICAgICAxOTQsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMjM5LFxuICAgICAgICA2NCxcbiAgICAgICAgMTI2LFxuICAgICAgICAxNjEsXG4gICAgICAgIDI3LFxuICAgICAgICAxODQsXG4gICAgICAgIDIxOSxcbiAgICAgICAgMTI0LFxuICAgICAgICAxODgsXG4gICAgICAgIDQ2LFxuICAgICAgICA1NSxcbiAgICAgICAgMTcxLFxuICAgICAgICAxNjUsXG4gICAgICAgIDE0LFxuICAgICAgICAxNjcsXG4gICAgICAgIDMyLFxuICAgICAgICAxMjgsXG4gICAgICAgIDg0LFxuICAgICAgICA5OSxcbiAgICAgICAgNzUsXG4gICAgICAgIDEyMlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMDUsXG4gICAgICAgIDkyLFxuICAgICAgICAyNDAsXG4gICAgICAgIDIwNixcbiAgICAgICAgMTY3LFxuICAgICAgICAyMSxcbiAgICAgICAgNzcsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjAyLFxuICAgICAgICAxMTgsXG4gICAgICAgIDE1OSxcbiAgICAgICAgNzMsXG4gICAgICAgIDEyLFxuICAgICAgICA2MyxcbiAgICAgICAgNTQsXG4gICAgICAgIDE5OSxcbiAgICAgICAgNDIsXG4gICAgICAgIDM1LFxuICAgICAgICAyMTcsXG4gICAgICAgIDIsXG4gICAgICAgIDIyMSxcbiAgICAgICAgMTgyLFxuICAgICAgICAxOTAsXG4gICAgICAgIDUsXG4gICAgICAgIDIxNCxcbiAgICAgICAgNDEsXG4gICAgICAgIDQyLFxuICAgICAgICAxMzQsXG4gICAgICAgIDIyNCxcbiAgICAgICAgNDcsXG4gICAgICAgIDIzNixcbiAgICAgICAgODRcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTYwLFxuICAgICAgICAgIDMyLFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDQ3LFxuICAgICAgICAgIDEzMCxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICAyLFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMjEwLFxuICAgICAgICAgIDEzNixcbiAgICAgICAgICAzNCxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMTMzLFxuICAgICAgICAgIDgsXG4gICAgICAgICAgMzMsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgNzMsXG4gICAgICAgICAgMTUsXG4gICAgICAgICAgMjA2LFxuICAgICAgICAgIDE3OSxcbiAgICAgICAgICAyMjAsXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMjAxLFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAxODQsXG4gICAgICAgICAgODksXG4gICAgICAgICAgNTgsXG4gICAgICAgICAgNzJcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNjAsXG4gICAgICAgICAgMTksXG4gICAgICAgICAgMjA3LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDcwLFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDE0MSxcbiAgICAgICAgICAxNSxcbiAgICAgICAgICAyMTIsXG4gICAgICAgICAgMTA3LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDEzMSxcbiAgICAgICAgICAzMSxcbiAgICAgICAgICAyMDMsXG4gICAgICAgICAgMTUwLFxuICAgICAgICAgIDEzMyxcbiAgICAgICAgICAyMjYsXG4gICAgICAgICAgNzgsXG4gICAgICAgICAgMTk3LFxuICAgICAgICAgIDk4LFxuICAgICAgICAgIDIyLFxuICAgICAgICAgIDE1LFxuICAgICAgICAgIDE1OCxcbiAgICAgICAgICAzLFxuICAgICAgICAgIDIxOCxcbiAgICAgICAgICAzMCxcbiAgICAgICAgICA5MCxcbiAgICAgICAgICAxNDAsXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDY1LFxuICAgICAgICAgIDEyOCxcbiAgICAgICAgICA2OFxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDY1LFxuICAgICAgICAxNzksXG4gICAgICAgIDI0MSxcbiAgICAgICAgNTksXG4gICAgICAgIDIwNixcbiAgICAgICAgMTI4LFxuICAgICAgICA2NixcbiAgICAgICAgMTM0LFxuICAgICAgICAxMTQsXG4gICAgICAgIDYzLFxuICAgICAgICAxNDksXG4gICAgICAgIDE2MyxcbiAgICAgICAgMTAyLFxuICAgICAgICAyMTMsXG4gICAgICAgIDczLFxuICAgICAgICAxOTgsXG4gICAgICAgIDIyNyxcbiAgICAgICAgMTcyLFxuICAgICAgICAxNzgsXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjM3LFxuICAgICAgICA0MixcbiAgICAgICAgNSxcbiAgICAgICAgMTExLFxuICAgICAgICA4LFxuICAgICAgICA0NixcbiAgICAgICAgMzcsXG4gICAgICAgIDE1NCxcbiAgICAgICAgMTY1LFxuICAgICAgICAyMzYsXG4gICAgICAgIDE0LFxuICAgICAgICAxMzUsXG4gICAgICAgIDM3LFxuICAgICAgICAxODQsXG4gICAgICAgIDYyLFxuICAgICAgICAxMzAsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMjIyLFxuICAgICAgICA5NixcbiAgICAgICAgMTYxLFxuICAgICAgICAyNixcbiAgICAgICAgMTU1LFxuICAgICAgICAyMTIsXG4gICAgICAgIDg0LFxuICAgICAgICAyMzQsXG4gICAgICAgIDExMCxcbiAgICAgICAgMTg5LFxuICAgICAgICAxODYsXG4gICAgICAgIDExLFxuICAgICAgICAzMSxcbiAgICAgICAgMTAsXG4gICAgICAgIDQwLFxuICAgICAgICAxOTgsXG4gICAgICAgIDI5LFxuICAgICAgICA5MixcbiAgICAgICAgMjE1LFxuICAgICAgICAxMSxcbiAgICAgICAgOTYsXG4gICAgICAgIDYxLFxuICAgICAgICAxNTAsXG4gICAgICAgIDI1MSxcbiAgICAgICAgOTMsXG4gICAgICAgIDY0LFxuICAgICAgICAxMFxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTkyLFxuICBcImFkdlNlY3JldEtleVwiOiBcIk03TDFuLzNyK0M1ekVjNWhXL0tmWU8yS0crbDJLNmtBc3pRKzNicVVMTUk9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiMjM0ODE0MDUxNDk5OEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImZyb21NZVwiOiB0cnVlLFxuICAgICAgICBcImlkXCI6IFwiN0VDQzFBQzYzQkIzMzU5NkFGMjZCNzgwODdDNDZGNTBcIlxuICAgICAgfSxcbiAgICAgIFwibWVzc2FnZVRpbWVzdGFtcFwiOiAxNzI2ODk2NzI3XG4gICAgfVxuICBdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMCxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcIlVJYzNIYU5IVGp5d1hfRktqOTRGbXdcIixcbiAgXCJwaG9uZUlkXCI6IFwiYTEzNDBmNTUtZTc5OC00MDc1LTlhZGMtYTA4ZTU0NDljN2E5XCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDE2OSxcbiAgICAgIDIwLFxuICAgICAgMjA4LFxuICAgICAgNDksXG4gICAgICAxNTEsXG4gICAgICA5OSxcbiAgICAgIDg0LFxuICAgICAgMTksXG4gICAgICAxODUsXG4gICAgICAyMCxcbiAgICAgIDI0MSxcbiAgICAgIDUwLFxuICAgICAgMjQ3LFxuICAgICAgNSxcbiAgICAgIDY5LFxuICAgICAgMSxcbiAgICAgIDE4NSxcbiAgICAgIDU1LFxuICAgICAgMTA4LFxuICAgICAgMTEyXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDEzMyxcbiAgICAgIDE2MSxcbiAgICAgIDE3OSxcbiAgICAgIDc4LFxuICAgICAgOTYsXG4gICAgICAyMTksXG4gICAgICAyNDEsXG4gICAgICAxMSxcbiAgICAgIDQsXG4gICAgICAxNSxcbiAgICAgIDg0LFxuICAgICAgMjExLFxuICAgICAgMTY0LFxuICAgICAgNTMsXG4gICAgICAyMTgsXG4gICAgICAxMDUsXG4gICAgICA1LFxuICAgICAgMTU4LFxuICAgICAgMTM4LFxuICAgICAgNjVcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiTjU4M1JCUUFcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDgxNDA1MTQ5OTg6MjBAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJzaGFmYWF0dWhhbGFkdTNcIixcbiAgICBcImxpZFwiOiBcIjI1MjE3NDgyNzI5MDc2NDoyMEBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNPQ2U3QzRReTdTNXR3WVlBU0FBS0FBPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcInErbS92bE5nZWp2L0c5VkdhTWN0b0JrZHFBaVMxWnJmWVZhNy9pUDhpU3c9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwia1BSOTh3ZlZZdUhDK3dHVnAwTEN3QldpMU9ObXRjVjY3MjljYXdZbVJGYVJ0amQ1Z1ZhTHhodExNL2IrblVzUUppTVZvR3JqL0QzVW1QMUZtUlRFQnc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiSFQ4MzVYaEV1SWxFVjk0cUNaTDJ6bktQOUFBRm9DaUVmMUVWOHJiYTlTU2Y0eEZiZzlOTlplWnRCUHJQc2g1d2ZSK1VOUGw2b3FJcEZFbGE3Nzh2QWc9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0ODE0MDUxNDk5ODoyMEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICAyMzMsXG4gICAgICAgICAgMTkxLFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICA5NixcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICA3MCxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDQ1LFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAyOSxcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgOCxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAzNSxcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgMTM3LFxuICAgICAgICAgIDQ0XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjY4OTY3MTksXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFEdVBcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUR1UC5qc29uIjogIntcImtleURhdGFcIjpcImd2elVRVTlZSndXTkhHbExLYS91clZqZ1BhOFpEdS9PaktOUmlWKzdRNkk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6OTgyNDI0MDAsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyNjg5NjczMjU1M1wifSIKfQ="=,  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
