const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "238140514998";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "♥️",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "It'x Suhail",

  sessionName:process.env.SESSION_ID || "SUHAIL_18_02_09_22_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMzIsXG4gICAgICAgIDE4NixcbiAgICAgICAgODcsXG4gICAgICAgIDE5OCxcbiAgICAgICAgOTIsXG4gICAgICAgIDE5NixcbiAgICAgICAgNTcsXG4gICAgICAgIDI0LFxuICAgICAgICAxNzgsXG4gICAgICAgIDE2MCxcbiAgICAgICAgNzgsXG4gICAgICAgIDgyLFxuICAgICAgICAxMSxcbiAgICAgICAgMTI3LFxuICAgICAgICA2MyxcbiAgICAgICAgMjE0LFxuICAgICAgICAxNTUsXG4gICAgICAgIDM5LFxuICAgICAgICAyMCxcbiAgICAgICAgMTA4LFxuICAgICAgICA2NyxcbiAgICAgICAgMjUwLFxuICAgICAgICAxMjUsXG4gICAgICAgIDgxLFxuICAgICAgICAyLFxuICAgICAgICAyMjQsXG4gICAgICAgIDQ3LFxuICAgICAgICA1OCxcbiAgICAgICAgODksXG4gICAgICAgIDQ4LFxuICAgICAgICAxMDMsXG4gICAgICAgIDY2XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDgxLFxuICAgICAgICAxMjQsXG4gICAgICAgIDE4MCxcbiAgICAgICAgMTY0LFxuICAgICAgICAyMDksXG4gICAgICAgIDE2OSxcbiAgICAgICAgMzAsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMjQ1LFxuICAgICAgICAxNzEsXG4gICAgICAgIDg5LFxuICAgICAgICAyOSxcbiAgICAgICAgMjM3LFxuICAgICAgICAxOTcsXG4gICAgICAgIDExNSxcbiAgICAgICAgMTk0LFxuICAgICAgICAxNTksXG4gICAgICAgIDE4NCxcbiAgICAgICAgMTE2LFxuICAgICAgICAxNTMsXG4gICAgICAgIDg5LFxuICAgICAgICAyMTEsXG4gICAgICAgIDIwMCxcbiAgICAgICAgNzAsXG4gICAgICAgIDY3LFxuICAgICAgICAzMCxcbiAgICAgICAgMTA3LFxuICAgICAgICAxMzQsXG4gICAgICAgIDgsXG4gICAgICAgIDkzLFxuICAgICAgICAxOTIsXG4gICAgICAgIDU3XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyMDgsXG4gICAgICAgIDk4LFxuICAgICAgICAxMTgsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMjMwLFxuICAgICAgICAyMTcsXG4gICAgICAgIDc1LFxuICAgICAgICAyMzIsXG4gICAgICAgIDI2LFxuICAgICAgICA3NyxcbiAgICAgICAgMzQsXG4gICAgICAgIDE4NixcbiAgICAgICAgODIsXG4gICAgICAgIDEzLFxuICAgICAgICA1MixcbiAgICAgICAgMTQ1LFxuICAgICAgICA5OCxcbiAgICAgICAgNDQsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTU5LFxuICAgICAgICAxNTQsXG4gICAgICAgIDE2MyxcbiAgICAgICAgMTM4LFxuICAgICAgICAyMDEsXG4gICAgICAgIDk2LFxuICAgICAgICAxMDgsXG4gICAgICAgIDIyMyxcbiAgICAgICAgNTEsXG4gICAgICAgIDEzMixcbiAgICAgICAgMjE0LFxuICAgICAgICA2MSxcbiAgICAgICAgNzlcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNjEsXG4gICAgICAgIDEyOCxcbiAgICAgICAgMTY3LFxuICAgICAgICAxMjAsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTcsXG4gICAgICAgIDU1LFxuICAgICAgICAxMjYsXG4gICAgICAgIDIzOCxcbiAgICAgICAgMjMsXG4gICAgICAgIDIxNCxcbiAgICAgICAgMjA5LFxuICAgICAgICAyNDIsXG4gICAgICAgIDU5LFxuICAgICAgICAzMSxcbiAgICAgICAgNzcsXG4gICAgICAgIDExNSxcbiAgICAgICAgNTYsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTA4LFxuICAgICAgICAxODUsXG4gICAgICAgIDc4LFxuICAgICAgICA5NyxcbiAgICAgICAgMTE1LFxuICAgICAgICAxMTUsXG4gICAgICAgIDY4LFxuICAgICAgICAxNDUsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTQ5LFxuICAgICAgICAxOTAsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMjdcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkSWRlbnRpdHlLZXlcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE4NCxcbiAgICAgICAgMjA0LFxuICAgICAgICAxNDQsXG4gICAgICAgIDk4LFxuICAgICAgICAxNjUsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMzcsXG4gICAgICAgIDkxLFxuICAgICAgICA5NyxcbiAgICAgICAgMTczLFxuICAgICAgICAxMixcbiAgICAgICAgMTM1LFxuICAgICAgICAxOTIsXG4gICAgICAgIDI2LFxuICAgICAgICA5OCxcbiAgICAgICAgMjIzLFxuICAgICAgICA1MixcbiAgICAgICAgMTU4LFxuICAgICAgICAxOTcsXG4gICAgICAgIDEyNCxcbiAgICAgICAgMjQ4LFxuICAgICAgICAxMjQsXG4gICAgICAgIDI1MyxcbiAgICAgICAgOSxcbiAgICAgICAgMjM4LFxuICAgICAgICAyMTMsXG4gICAgICAgIDIxMixcbiAgICAgICAgNDEsXG4gICAgICAgIDEyMyxcbiAgICAgICAgOTksXG4gICAgICAgIDE0NixcbiAgICAgICAgMTEzXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzOSxcbiAgICAgICAgNjIsXG4gICAgICAgIDgxLFxuICAgICAgICAxNSxcbiAgICAgICAgMTc1LFxuICAgICAgICAyMzMsXG4gICAgICAgIDE3NixcbiAgICAgICAgOTIsXG4gICAgICAgIDE1MSxcbiAgICAgICAgOTksXG4gICAgICAgIDgxLFxuICAgICAgICAxMjUsXG4gICAgICAgIDg2LFxuICAgICAgICAyMjAsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMjMwLFxuICAgICAgICA4OCxcbiAgICAgICAgMjUyLFxuICAgICAgICAxOTEsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTI5LFxuICAgICAgICA3OSxcbiAgICAgICAgMTA1LFxuICAgICAgICAxMTUsXG4gICAgICAgIDEzMCxcbiAgICAgICAgMjUsXG4gICAgICAgIDI0LFxuICAgICAgICAxNzcsXG4gICAgICAgIDEwMSxcbiAgICAgICAgODAsXG4gICAgICAgIDE0NCxcbiAgICAgICAgMzhcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMzIsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAyNCxcbiAgICAgICAgICA4NixcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgMTcyLFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTA0LFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICAyNCxcbiAgICAgICAgICAxNzEsXG4gICAgICAgICAgOCxcbiAgICAgICAgICA0NyxcbiAgICAgICAgICAxOTAsXG4gICAgICAgICAgMTI2LFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDgwLFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICA4LFxuICAgICAgICAgIDQ2LFxuICAgICAgICAgIDEyMSxcbiAgICAgICAgICA5MixcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAxNjQsXG4gICAgICAgICAgNyxcbiAgICAgICAgICA2N1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgMzksXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAxOTgsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDI4LFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDExOCxcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgMTkxLFxuICAgICAgICAgIDg5LFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTU4LFxuICAgICAgICAgIDIxNCxcbiAgICAgICAgICAxMTMsXG4gICAgICAgICAgMjMxLFxuICAgICAgICAgIDI0OCxcbiAgICAgICAgICAxNDcsXG4gICAgICAgICAgNTQsXG4gICAgICAgICAgODcsXG4gICAgICAgICAgNTIsXG4gICAgICAgICAgMjksXG4gICAgICAgICAgMTksXG4gICAgICAgICAgNTUsXG4gICAgICAgICAgMjMzLFxuICAgICAgICAgIDg2LFxuICAgICAgICAgIDE1MSxcbiAgICAgICAgICAxNzUsXG4gICAgICAgICAgMTA5XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTU0LFxuICAgICAgICAyNDMsXG4gICAgICAgIDksXG4gICAgICAgIDUsXG4gICAgICAgIDIyNSxcbiAgICAgICAgOTksXG4gICAgICAgIDIxNyxcbiAgICAgICAgMTE4LFxuICAgICAgICAyMTEsXG4gICAgICAgIDE4MixcbiAgICAgICAgMTQwLFxuICAgICAgICA2NixcbiAgICAgICAgOTcsXG4gICAgICAgIDE4NyxcbiAgICAgICAgMTMzLFxuICAgICAgICAyMDYsXG4gICAgICAgIDUwLFxuICAgICAgICAzMyxcbiAgICAgICAgMTAyLFxuICAgICAgICA5MixcbiAgICAgICAgMTQ3LFxuICAgICAgICA4OSxcbiAgICAgICAgMTI2LFxuICAgICAgICA3MCxcbiAgICAgICAgMTUsXG4gICAgICAgIDEyMyxcbiAgICAgICAgMjA5LFxuICAgICAgICAxNixcbiAgICAgICAgMzUsXG4gICAgICAgIDQ4LFxuICAgICAgICAxNjUsXG4gICAgICAgIDMwLFxuICAgICAgICAyMTksXG4gICAgICAgIDIwNyxcbiAgICAgICAgMjIsXG4gICAgICAgIDE5NSxcbiAgICAgICAgMjQzLFxuICAgICAgICA0OSxcbiAgICAgICAgNzcsXG4gICAgICAgIDEzNyxcbiAgICAgICAgNjQsXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTAwLFxuICAgICAgICAyMjcsXG4gICAgICAgIDE3NyxcbiAgICAgICAgNTksXG4gICAgICAgIDEzOCxcbiAgICAgICAgMTc1LFxuICAgICAgICA1OCxcbiAgICAgICAgMjU0LFxuICAgICAgICAxNzcsXG4gICAgICAgIDE1MixcbiAgICAgICAgMTkyLFxuICAgICAgICAxOSxcbiAgICAgICAgMTc2LFxuICAgICAgICA5LFxuICAgICAgICA0NyxcbiAgICAgICAgNDIsXG4gICAgICAgIDUxLFxuICAgICAgICAxMixcbiAgICAgICAgMTI3LFxuICAgICAgICAxMjgsXG4gICAgICAgIDI2LFxuICAgICAgICA2XG4gICAgICBdXG4gICAgfSxcbiAgICBcImtleUlkXCI6IDFcbiAgfSxcbiAgXCJyZWdpc3RyYXRpb25JZFwiOiAxMTUsXG4gIFwiYWR2U2VjcmV0S2V5XCI6IFwiUmVVNTQyUEZXNkZZLzhBczZ3RlRqUS8vQ0VXbDRQTHdsUzU4NTdXQzgvOD1cIixcbiAgXCJwcm9jZXNzZWRIaXN0b3J5TWVzc2FnZXNcIjogW10sXG4gIFwibmV4dFByZUtleUlkXCI6IDMxLFxuICBcImZpcnN0VW51cGxvYWRlZFByZUtleUlkXCI6IDMxLFxuICBcImFjY291bnRTeW5jQ291bnRlclwiOiAwLFxuICBcImFjY291bnRTZXR0aW5nc1wiOiB7XG4gICAgXCJ1bmFyY2hpdmVDaGF0c1wiOiBmYWxzZVxuICB9LFxuICBcImRldmljZUlkXCI6IFwiaE5Zbk9oSDJSWkdqUEtCT2ktcVNsd1wiLFxuICBcInBob25lSWRcIjogXCI2ZmMzZDFiNS0yMWY4LTRkOWEtODY1MS00MDk3M2U4OWM2MDdcIixcbiAgXCJpZGVudGl0eUlkXCI6IHtcbiAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICBcImRhdGFcIjogW1xuICAgICAgMTU2LFxuICAgICAgMTM1LFxuICAgICAgMTQyLFxuICAgICAgMjE4LFxuICAgICAgMTAxLFxuICAgICAgMTcwLFxuICAgICAgNTUsXG4gICAgICAyMixcbiAgICAgIDE3NCxcbiAgICAgIDU5LFxuICAgICAgMTExLFxuICAgICAgMTMwLFxuICAgICAgMjM0LFxuICAgICAgMTUzLFxuICAgICAgMjEwLFxuICAgICAgMTc4LFxuICAgICAgMTgxLFxuICAgICAgMTA3LFxuICAgICAgMTI5LFxuICAgICAgMTA2XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDc5LFxuICAgICAgMCxcbiAgICAgIDQzLFxuICAgICAgMTMsXG4gICAgICAxMDcsXG4gICAgICAxNDMsXG4gICAgICA0NixcbiAgICAgIDc0LFxuICAgICAgMjYsXG4gICAgICAxOTYsXG4gICAgICAxMzYsXG4gICAgICAyNDIsXG4gICAgICAxOTcsXG4gICAgICA0NyxcbiAgICAgIDE0NyxcbiAgICAgIDE0NixcbiAgICAgIDEsXG4gICAgICAzNSxcbiAgICAgIDMsXG4gICAgICAxNjNcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiUTJMV1FQQ1BcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjIzNDgxNDA1MTQ5OTg6MjFAcy53aGF0c2FwcC5uZXRcIixcbiAgICBcIm5hbWVcIjogXCJzaGFmYWF0dWhhbGFkdTNcIixcbiAgICBcImxpZFwiOiBcIjI1MjE3NDgyNzI5MDc2NDoyMUBsaWRcIlxuICB9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNPQ2U3QzRRczdmQnR3WVlBaUFBS0FBPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcInErbS92bE5nZWp2L0c5VkdhTWN0b0JrZHFBaVMxWnJmWVZhNy9pUDhpU3c9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiV082aXEzVFI2eUYrNElPR1F0YS9QYjNqYlcyZ3VmQTllTlIzVXU0ZUdHaHpBZ1UvOXlnVnZkNkRVUjIvOTAwUGFGWXYxSnR4M3dHQ1ZsMHFZdUVjQWc9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiZTF4a0pNV1JoQzJZZFdITEhMbTAveC8zSStMNm9vcjdKWTBNeUdVRlVUU1B6MlZEWDN5T252RGFtQzhJb0JDWXY2cXpTU3JWVmVQVTZ0SEJjQ0FDQkE9PVwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0ODE0MDUxNDk5ODoyMUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDE3MSxcbiAgICAgICAgICAyMzMsXG4gICAgICAgICAgMTkxLFxuICAgICAgICAgIDE5MCxcbiAgICAgICAgICA4MyxcbiAgICAgICAgICA5NixcbiAgICAgICAgICAxMjIsXG4gICAgICAgICAgNTksXG4gICAgICAgICAgMjU1LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICA3MCxcbiAgICAgICAgICAxMDQsXG4gICAgICAgICAgMTk5LFxuICAgICAgICAgIDQ1LFxuICAgICAgICAgIDE2MCxcbiAgICAgICAgICAyNSxcbiAgICAgICAgICAyOSxcbiAgICAgICAgICAxNjgsXG4gICAgICAgICAgOCxcbiAgICAgICAgICAxNDYsXG4gICAgICAgICAgMjEzLFxuICAgICAgICAgIDE1NCxcbiAgICAgICAgICAyMjMsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgODYsXG4gICAgICAgICAgMTg3LFxuICAgICAgICAgIDI1NCxcbiAgICAgICAgICAzNSxcbiAgICAgICAgICAyNTIsXG4gICAgICAgICAgMTM3LFxuICAgICAgICAgIDQ0XG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9XG4gIF0sXG4gIFwicGxhdGZvcm1cIjogXCJzbWJhXCIsXG4gIFwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wXCI6IDE3MjcwMjgxNTIsXG4gIFwibXlBcHBTdGF0ZUtleUlkXCI6IFwiQUFBQUFEdVBcIlxufSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUR1UC5qc29uIjogIntcImtleURhdGFcIjpcImd2elVRVTlZSndXTkhHbExLYS91clZqZ1BhOFpEdS9PaktOUmlWKzdRNkk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6OTgyNDI0MDAsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMTcyNjg5NjczMjU1M1wifSIKfQ==",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
